spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7890/trabajofinal
    username: postgres
    password: admin
    
---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:7890/trabajofinal
    username: postgres
    password: admin

